/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/__api__/Container": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["Container"][];
            "application/json": components["schemas"]["Container"][];
            "text/json": components["schemas"]["Container"][];
          };
        };
      };
    };
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ContainerModel"];
          "text/json": components["schemas"]["ContainerModel"];
          "application/*+json": components["schemas"]["ContainerModel"];
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
  "/__api__/Container/run/{id}": {
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Container: {
      project?: components["schemas"]["IProject"];
      created?: boolean;
      running?: boolean;
    };
    ContainerModel: {
      name?: string | null;
    };
    IProject: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
