import createClient from "openapi-fetch";
import type { paths, components } from "./schema"; // generated by openapi-typescript

export const httpClient = createClient<paths>();

export type Schemas = components["schemas"]