/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/__api__/Project/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["WebProject"];
            "application/json": components["schemas"]["WebProject"];
            "text/json": components["schemas"]["WebProject"];
          };
        };
      };
    };
  };
  "/__api__/Project": {
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["WebProject"][];
            "application/json": components["schemas"]["WebProject"][];
            "text/json": components["schemas"]["WebProject"][];
          };
        };
      };
    };
    post: {
      parameters: {
        query?: {
          name?: string;
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "text/plain": components["schemas"]["WebProject"];
            "application/json": components["schemas"]["WebProject"];
            "text/json": components["schemas"]["WebProject"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    WebProject: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
